[pytest]
DJANGO_SETTINGS_MODULE = 高校体育场馆管理系统.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --reuse-db --cov=app01 --cov-report=term-missing
testpaths = app01/tests
