"""
Django settings for 高校体育场馆管理系统 project.

配置原则(P0 商业化改造):
- 所有敏感信息(SECRET_KEY、数据库密码、DEBUG)通过环境变量读取,见 .env / .env.example
- 使用 django-environ 统一管理
- .env 文件被 .gitignore 忽略,绝不提交版本库

Generated by 'django-admin startproject' using Django 4.0.1.
"""

import os.path
from pathlib import Path

import environ
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ===== 环境变量读取 =====
# 声明每个变量的类型与默认值,确保类型安全
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    SECURE_SSL_REDIRECT=(bool, False),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SECURE=(bool, False),
    HSTS_SECONDS=(int, 0),
)

# 从 .env 文件读取(开发环境);生产环境由容器/系统环境变量注入
# 文件不存在时静默跳过(不报错),由系统环境变量接管
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    environ.Env.read_env(str(_env_file))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 第三方(P2a)
    'corsheaders',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # 异步(P3b)
    'django_celery_beat',
    # 业务
    'app01.apps.App01Config',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # P2a:跨域,须置于 CommonMiddleware 之前
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app01.middleware.auth.AuthMiddleware',
]

ROOT_URLCONF = '高校体育场馆管理系统.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '高校体育场馆管理系统.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# 通过 DATABASE_URL 环境变量配置,格式: mysql://user:password@host:port/dbname
DATABASES = {
    'default': env.db('DATABASE_URL'),
}

# 数据库连接复用,减少每次请求新建连接的开销(P1 可调优)
CONN_MAX_AGE = env.int('CONN_MAX_AGE', default=60)


# 自定义用户模型(P1:Account 继承 AbstractUser,命名为 CustomUser)
# 必须在第一次 makemigrations 之前配置,否则切换成本极高
AUTH_USER_MODEL = 'app01.CustomUser'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# 修复:原值为 UTC,导致用户看到的时间偏差 8 小时
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# collectstatic 输出目录,生产环境由 nginx 托管
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 媒体文件(用户上传)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 文件上传大小限制(防 DoS)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024  # 5MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ====================================================================
# 安全配置(P0 商业化改造)
# 生产环境在 .env 中开启:SECURE_SSL_REDIRECT=True, *_COOKIE_SECURE=True, HSTS_SECONDS>0
# ====================================================================

# HTTPS 跳转(仅在确认有 HTTPS 后开启)
SECURE_SSL_REDIRECT = env('SECURE_SSL_REDIRECT')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookie 安全标志(生产环境 + HTTPS 时设 True)
SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE')
CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE')
SESSION_COOKIE_HTTPONLY = True  # JavaScript 无法读取 session cookie(默认即为 True,显式声明)
CSRF_COOKIE_HTTPONLY = False  # 需允许 JS 读取 csrftoken 以发送 AJAX 请求
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# HSTS(仅在确认长期使用 HTTPS 后开启)
SECURE_HSTS_SECONDS = env('HSTS_SECONDS')
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 防止 MIME 类型嗅探
SECURE_CONTENT_TYPE_NOSNIFF = True

# 点击劫持防护(收紧为 DENY:本系统无需被嵌入 iframe)
X_FRAME_OPTIONS = 'DENY'

# Session 过期时间(与原代码一致:7 天)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7


# ====================================================================
# 日志配置(P0 商业化改造:补齐安全审计与错误日志)
# ====================================================================

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}:{lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # 安全事件:登录失败、CSRF 失败、可疑请求等
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'security.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        # 应用错误(5xx 等)
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'error.log',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
            'level': 'ERROR',
        },
    },
    'loggers': {
        # Django 安全信号(csrf, auth 等)
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # 业务日志
        'app01': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Django 框架本身
        'django': {
            'handlers': ['console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# ====================================================================
# DRF + JWT + 缓存 + 跨域(P2a 商业化改造)
# ====================================================================
from datetime import timedelta  # noqa: E402

# Django REST Framework
REST_FRAMEWORK = {
    # Session(SSR admin 共存)+ JWT(API)双认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# JWT 有效期与轮换(blacklist 依赖 token_blacklist app + migrate)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# 缓存(生产 Redis;本地无 Redis 时用 locmem 兜底,environ 不支持 locmem scheme 故手动判断)
_redis_url = env('REDIS_URL', default='')
if _redis_url.startswith(('redis://', 'rediss://')):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'sports-venue-cache',
        }
    }

# Celery(P3b):与 CACHES 同判断;locmem:// 是 Django cache scheme,非 celery broker
# 无真实 Redis(本地/测试 .env 配 locmem:// 或空)→ EAGER 同步执行,免 broker
# 注意:broker 用 memory://(kombu transport),result backend 用 cache+memory://(celery cache 后端)
#   — 两者 scheme 不同,memory:// 作 result backend 会触发 ModuleNotFoundError: No module named 'memory'
_has_real_redis = _redis_url.startswith(('redis://', 'rediss://'))
CELERY_BROKER_URL = _redis_url if _has_real_redis else 'memory://'
CELERY_RESULT_BACKEND = _redis_url if _has_real_redis else 'cache+memory://'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = not _has_real_redis
CELERY_TASK_EAGER_PROPAGATES = True  # EAGER 下异常直接抛,便于测试
CELERY_BEAT_SCHEDULE = {
    'scan-no-shows-every-30min': {
        'task': 'app01.tasks.scan_no_shows',
        'schedule': crontab(minute='*/30'),
        'args': (30,),  # grace_minutes
    },
}

# 跨域(前端 Vue dev server,默认 5173)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=['http://localhost:5173'])
CORS_ALLOW_CREDENTIALS = True
