# Generated by Django 4.0.1 on 2022-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=32, verbose_name='证件号')),
                ('password', models.CharField(default='123456', max_length=64, verbose_name='密码')),
            ],
        ),
    ]
