# Generated by Django 5.1.2 on 2026-07-02 14:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='代码')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_number', models.CharField(max_length=32, unique=True, verbose_name='学号/手机号')),
                ('role', models.CharField(choices=[('student', '学生/普通用户'), ('staff', '工作人员'), ('admin', '管理员')], default='student', max_length=16, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('college', models.CharField(blank=True, max_length=64, verbose_name='学院')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32, verbose_name='动作')),
                ('target_model', models.CharField(max_length=64, verbose_name='目标模型')),
                ('target_id', models.CharField(max_length=32, verbose_name='目标 ID')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('booking_submitted', '预约已提交'), ('booking_approved', '预约已通过'), ('booking_rejected', '预约已拒绝'), ('booking_reminder', '预约即将开始'), ('booking_no_show', '预约违约'), ('system', '系统通知')], max_length=32, verbose_name='类型')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='场地')),
                ('people', models.CharField(max_length=32, verbose_name='容纳人数(兼容)')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='容量')),
                ('place_type', models.CharField(choices=[('badminton', '羽毛球馆'), ('basketball', '篮球场'), ('table_tennis', '乒乓球馆'), ('gym', '健身房'), ('other', '其他')], default='other', max_length=32, verbose_name='类型')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='place_covers/', verbose_name='封面图')),
                ('use', models.SmallIntegerField(choices=[(0, '不可用'), (1, '可使用')], default=1, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='app01.campus', verbose_name='校区')),
            ],
            options={
                'verbose_name': '场地',
                'verbose_name_plural': '场地',
                'unique_together': {('name', 'campus')},
            },
        ),
        migrations.CreateModel(
            name='BookingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(blank=True, max_length=32, verbose_name='场地类型')),
                ('advance_days', models.PositiveIntegerField(default=7, verbose_name='提前可约天数')),
                ('daily_limit_per_user', models.PositiveIntegerField(default=1, verbose_name='每人每日上限')),
                ('cancel_deadline_hours', models.PositiveIntegerField(default=2, verbose_name='取消时限(小时)')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app01.place', verbose_name='适用场地')),
            ],
            options={
                'verbose_name': '预约规则',
                'verbose_name_plural': '预约规则',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='app01.campus', verbose_name='校区')),
            ],
            options={
                'verbose_name': '时段',
                'verbose_name_plural': '时段',
                'ordering': ['sort_order', 'start_time'],
                'unique_together': {('campus', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=32, verbose_name='使用人数')),
                ('date', models.CharField(max_length=32, verbose_name='日期(兼容)')),
                ('time', models.CharField(max_length=32, verbose_name='时间段(兼容)')),
                ('status', models.SmallIntegerField(choices=[(0, '待审批'), (1, '已通过'), (2, '已拒绝'), (3, '已取消'), (4, '已完成'), (5, '已违约')], default=0, verbose_name='状态')),
                ('booking_date', models.DateField(blank=True, null=True, verbose_name='预约日期')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='拒绝原因')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='预订人')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='app01.campus', verbose_name='校区')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='app01.place', verbose_name='场地')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app01.timeslot', verbose_name='时段')),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'indexes': [models.Index(fields=['place_name', 'date', 'time'], name='idx_book_place_date_time'), models.Index(fields=['book_name', 'booking_date'], name='idx_book_user_date')],
            },
        ),
    ]
