# Generated by Django 4.0.1 on 2022-03-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_account_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='场地')),
                ('people', models.CharField(max_length=32, verbose_name='容纳人数')),
                ('campus', models.CharField(max_length=32, verbose_name='所属校区')),
                ('use', models.SmallIntegerField(choices=[(0, '不可用'), (1, '可使用')], default=1, verbose_name='状态')),
            ],
        ),
    ]
