# Generated by Django 4.0.3 on 2022-04-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_regaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegAccount',
        ),
    ]
