# Generated by Django 4.0.3 on 2022-04-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_delete_regaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=32, verbose_name='预订人')),
                ('place_name', models.CharField(max_length=32, verbose_name='场地')),
                ('people', models.CharField(max_length=32, verbose_name='人数')),
                ('date', models.CharField(max_length=32, verbose_name='日期')),
                ('time', models.CharField(max_length=32, verbose_name='时间段')),
                ('status', models.SmallIntegerField(choices=[(0, '待审批'), (1, '已审批')], default=0, verbose_name='状态')),
            ],
        ),
    ]
