# Generated by Django 4.0.3 on 2022-04-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.account', verbose_name='预订人'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=32, verbose_name='日 期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.CharField(max_length=32, verbose_name='人 数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='place_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.place', verbose_name='场 地'),
        ),
    ]
