# Generated by Django 4.0.3 on 2022-04-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_book_book_name_alter_book_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='campus',
            field=models.SmallIntegerField(choices=[(1, '东校区'), (2, '白云校区')], default=1, verbose_name='所属校区'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.CharField(max_length=32, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.CharField(max_length=32, verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='place_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.place', verbose_name='场地'),
        ),
    ]
