# Generated by Django 4.0.3 on 2022-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_book_campus_alter_book_date_alter_book_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.CharField(max_length=32, verbose_name='使用人数'),
        ),
    ]
