# Generated by Django 4.0.3 on 2022-04-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_book_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='campus',
            field=models.CharField(max_length=32, verbose_name='所属校区'),
        ),
    ]
